### ISSUE TITLE
How to update the map_info field in the JSON files???

### ISSUE THREAD

**Issue by happy-yan** [memberRE/AsyncDriver#3]
"update the map_info field in the JSON files to the corresponding file's absolute path.” 
 May I ask what the absolute path refers to here? I didn't find these npz paths, can you provide a more specific expression?

**Comment by happy-yan** [comment]
Where is your .npz data?

**Comment by memberRE** [comment]
The .npz data is in map_v2.tar.
https://huggingface.co/datasets/Member22335/AsyncDriver/tree/main

**Comment by happy-yan** [comment]
thank u~
